### ISSUE TITLE
Collaboration proposal

### ISSUE THREAD

**Issue by ronisbr** [sisl/SatelliteDynamics.jl#1]
Hi @duncan-eddy !

It is very nice to see people from space engineering using Julia. We are few people but we are creating good packages.

I am seeing that your effort here is to produce something that is already done by [SatelliteToolbox.jl](https://github.com/JuliaSpace/SatelliteToolbox.jl) and [ReferenceFrameRotations.jl](https://github.com/JuliaSpace/ReferenceFrameRotations.jl).

Wouldn’t it be more productive if we merge our efforts?

**Comment by duncaneddy** [comment]
Hi @ronisbr,

Thank you for the warm welcome to the Julia space engineering community. It's great to be here!

I'm definitely willing to collaborate on efforts as able, and am open to the possiblility of merging efforts in the future. However, I am reluctant to undertake a full merge of codebases at the moment for a few reasons:

1. This work represents an astrodynamics API which has existed in multiple languages and various forms over the last 6 years. This is the first opportunity I have had to release it as open source. There are a few more projects I'm working on finishing up and releasing that rely on the interface this repository presents. I'm slightly time constrained currently as I'm both working full time and finishing my PhD, so I don't have the bandwidth to rearchitect that much code to rearchitect and merge with an existing repository currently.
2. There are a few others who rely on this interface for their own research and work as well. The design of this API is quite deliberate and is the result of lots of feedback and iterations with regards to correctness, usability, and composability. 
3. I'm fairly particular on how certain aspects are designed (time, function syntax, reference frames) because I think getting it right provides enormous user benefit. I figure this would take some time to work through in a full merge of efforts that could take some time to resolve, but I would be open to planning towards a future release merging efforts. 
4. Implementing these models I find greatly helps my own learning and understanding.

There are a couple features I'm really glad to see already exist in  [SatelliteToolbox.jl](https://github.com/JuliaSpace/SatelliteToolbox.jl), which I am glad I don't have to reinvent the wheel for (atmospheric models in particular).

**Comment by ronisbr** [comment]
Excellent! Makes sense. If you need any help to use a feature in SatelliteToolbox, let me know.

Let’s try to make Julia the best language for space engineering! 😁

**Comment by duncaneddy** [comment]
Closing for now to keep issues fresh.
