### ISSUE TITLE
StaticArrays version issue

### ISSUE THREAD

**Issue by kevin-tracy** [sisl/SatelliteDynamics.jl#9]
Similar to [this issue](https://github.com/sisl/SatelliteDynamics.jl/issues/8), I am still having trouble with dependencies. If I start an environment with just SatelliteDynamics and StaticArrays, it restricts the version of StaticArrays to v0.11.1. This causes issues with multiple other packages, and I'm not sure how to fix it. Here is an example of what happens when I try to update StaticArrays.
```
(testenv) pkg> st
Status `~/devel/GravNav/testenv/Project.toml`
  [0e7c1a32] SatelliteDynamics v0.4.1
  [90137ffa] StaticArrays v0.11.1

(testenv) pkg> up StaticArrays
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
No Changes to `~/devel/GravNav/testenv/Project.toml`
No Changes to `~/devel/GravNav/testenv/Manifest.toml`
```
Thank you for the help as always, Duncan!

**Comment by duncaneddy** [comment]
Sorry for the slow response.

This is due to the fact that for a very long time StaticArrays was pre-1.0 which has significant implications for package compatibility and requires frequent compatibility revision (https://julialang.github.io/Pkg.jl/v1/compatibility/). In the future I'm happy to accept pull requests updating compat that fix these types of issues. But with the 1.0 release of StaticArrays it should be a less frequent issue.

This is incorporated into the v0.4.2 release I just cut.
